"""
AGEVAL Harmonization — Unified Baseline + Endline Analysis App
Run:  python -m streamlit run harmonization/01_code/app.py

Wraps the harmonization pipeline steps into a single clickable app, the
same way baseline/01_code/app.py wraps the individual survey steps. All
folders are resolved from `s00_harmonizationConfig.yaml`.

This wires in Step 1 (Dictionary Merge), Step 2 (Combine into a Long
Database), Step 3 (Treatment Assignment), Step 4 (Baseline/Endline
Quality Check), and Step 5 (Comparison Plots). Additional steps
(regressions, etc. on the combined baseline+endline data) will be added
as their own s0N_*.py modules and new pages below, following the same
pattern as the individual app.py.

NOTE: save this file as `harmonization/01_code/app.py` alongside
`s00_harmonizationConfig.yaml`, `s01_dictionary_merge.py`,
`s02_combine_long.py`, `s03_treatment_assignment.py`,
`s04_quality_check.py` and `s05_comparison_plots.py`. It is named
`app_harmonization.py` here only to avoid clashing with the individual
pipeline's `app.py` when both are downloaded together.
"""

import streamlit as st
import os
import sys
import glob
import yaml

# Make sibling scripts importable regardless of the working directory
SCRIPTS_DIR = os.path.dirname(os.path.abspath(__file__))
if SCRIPTS_DIR not in sys.path:
    sys.path.insert(0, SCRIPTS_DIR)

import s01_dictionary_merge as s01
import s02_combine_long as s02
import s03_treatment_assignment as s03
import s04_quality_check as s04
import s05_comparison_plots as s05

# ── Config-driven paths (single source of truth: s00_harmonizationConfig.yaml) ─
CFG = os.path.join(SCRIPTS_DIR, "s00_harmonizationConfig.yaml")
with open(CFG, "r") as f:
    config = yaml.safe_load(f)

BASE        = os.path.normpath(os.path.join(os.path.dirname(CFG), config["paths"]["base"]))
MASTER      = os.path.join(BASE, config["paths"]["dictionary_master"])
DICT_BASE   = os.path.join(BASE, config["paths"]["dictionary_baseline"])
DICT_END    = os.path.join(BASE, config["paths"]["dictionary_endline"])
DICT_HARM   = os.path.join(BASE, config["paths"]["dictionary_harmonization"])
DATA_HARM_DIR = os.path.join(BASE, config["paths"]["data_harmonization"])
TREATMENT_PATH = os.path.join(BASE, config["paths"]["treatment_assignment"])
TREATMENT_OUT  = os.path.join(DATA_HARM_DIR, config.get("harmonize", {}).get("long_treatment_filename", "data_long_treatment.csv"))
OUTPUTS_QUALITY_DIR = os.path.join(BASE, config["paths"]["outputs_quality"])
OUTPUTS_PLOTS_DIR = os.path.join(BASE, config["paths"]["outputs_plots"])

st.set_page_config(page_title="AGEVAL Harmonization", layout="wide", page_icon="🌱")


# ── Helpers ──────────────────────────────────────────────────────────────────
def exists(path):
    return bool(path) and os.path.exists(path)


def status_badge(ok):
    return "🟢" if ok else "⚪"


# ── Sidebar navigation ───────────────────────────────────────────────────────
st.sidebar.title("🌱 AGEVAL — Harmonization")
st.sidebar.caption("Baseline + endline combined analysis pipeline")

pipeline_status = {
    "1. Dictionary Merge": exists(DICT_HARM),
    "2. Combine Long Database": os.path.isdir(DATA_HARM_DIR) and len(os.listdir(DATA_HARM_DIR)) > 0,
    "3. Treatment Assignment": exists(TREATMENT_OUT),
    "4. Quality Check": os.path.isdir(OUTPUTS_QUALITY_DIR) and len(os.listdir(OUTPUTS_QUALITY_DIR)) > 0,
    "5. Comparison Plots": os.path.isdir(OUTPUTS_PLOTS_DIR) and len(os.listdir(OUTPUTS_PLOTS_DIR)) > 0,
    # Future steps (regressions on the combined baseline+endline data)
    # will be added here, e.g.:
    # "6. Regressions":         ...,
}

page = st.sidebar.radio(
    "Pipeline step",
    list(pipeline_status.keys()),
    format_func=lambda p: f"{status_badge(pipeline_status[p])}  {p}",
)

st.sidebar.markdown("---")
st.sidebar.caption(f"Project base:\n`{os.path.abspath(BASE)}`")
with st.sidebar.expander("Expected folder layout"):
    st.code(
        "dictionary/variables_master.xlsx\n"
        "baseline/02_dictionary/variables_personalized.csv   (from baseline pipeline Step 1)\n"
        "endline/02_dictionary/variables_personalized.csv    (from endline pipeline Step 1)\n"
        "harmonization/\n"
        "├── 02_dictionary/variables_personalized.csv   (generated by Step 1 below)\n"
        "├── 03_data/                    (combined baseline+endline data, and +treatment)\n"
        "├── 04_treatmentAssignment/treatment_assignment.xlsx\n"
        "├── 05_qualityCheck/\n"
        "├── 06_plots/\n"
        "└── 07_regressions/",
        language="text",
    )


# ── Page 1: Dictionary Merge ──────────────────────────────────────────────────
if page == "1. Dictionary Merge":
    s01.render(standalone=False)

# ── Page 2: Combine into Long Database ────────────────────────────────────────
elif page == "2. Combine Long Database":
    s02.render(standalone=False)

# ── Page 3: Treatment Assignment ──────────────────────────────────────────────
elif page == "3. Treatment Assignment":
    s03.render(standalone=False)

# ── Page 4: Quality Check ─────────────────────────────────────────────────────
elif page == "4. Quality Check":
    s04.render(standalone=False)

# ── Page 5: Comparison Plots ──────────────────────────────────────────────────
elif page == "5. Comparison Plots":
    s05.render(standalone=False)

# Future pages go here, following the same pattern as the individual app.py:
# elif page == "6. Regressions":
#     s06.render(standalone=False)