"""
AGEVAL Harmonization — Unified Baseline + Endline Analysis App
Run:  python -m streamlit run harmonization/01_code/app_harmonization.py

Wraps the harmonization pipeline steps into a single clickable app, the
same way baseline/01_code/app.py wraps the individual survey steps. All
folders are resolved from `s00_harmonizationConfig.yaml`.

For now this only wires in Step 1 (Dictionary Merge). Additional steps
(quality checks, plots, regressions, etc. on the combined baseline+endline
data) will be added as their own s0N_*.py modules and new pages below,
following the same pattern as the individual app.py.

NOTE: save this file as `harmonization/01_code/app.py` alongside
`s00_harmonizationConfig.yaml` and `s01_dictionary_merge.py`. It is named
`app_harmonization.py` here only to avoid clashing with the individual
pipeline's `app.py` when both are downloaded together.
"""

import streamlit as st
import os
import sys
import glob
import yaml

# Make sibling scripts importable regardless of the working directory
SCRIPTS_DIR = os.path.dirname(os.path.abspath(__file__))
if SCRIPTS_DIR not in sys.path:
    sys.path.insert(0, SCRIPTS_DIR)

import s01_dictionary_merge as s01

# ── Config-driven paths (single source of truth: s00_harmonizationConfig.yaml) ─
CFG = os.path.join(SCRIPTS_DIR, "s00_harmonizationConfig.yaml")
with open(CFG, "r") as f:
    config = yaml.safe_load(f)

BASE        = os.path.normpath(os.path.join(os.path.dirname(CFG), config["paths"]["base"]))
MASTER      = os.path.join(BASE, config["paths"]["dictionary_master"])
DICT_BASE   = os.path.join(BASE, config["paths"]["dictionary_baseline"])
DICT_END    = os.path.join(BASE, config["paths"]["dictionary_endline"])
DICT_HARM   = os.path.join(BASE, config["paths"]["dictionary_harmonization"])

st.set_page_config(page_title="AGEVAL Harmonization", layout="wide", page_icon="🌱")


# ── Helpers ──────────────────────────────────────────────────────────────────
def exists(path):
    return bool(path) and os.path.exists(path)


def status_badge(ok):
    return "🟢" if ok else "⚪"


# ── Sidebar navigation ───────────────────────────────────────────────────────
st.sidebar.title("🌱 AGEVAL — Harmonization")
st.sidebar.caption("Baseline + endline combined analysis pipeline")

pipeline_status = {
    "1. Dictionary Merge": exists(DICT_HARM),
    # Future steps (quality checks, plots, regressions on the combined
    # baseline+endline data) will be added here, e.g.:
    # "2. Combine Data":        ...,
    # "3. Quality Check":       ...,
    # "4. Plots":               ...,
    # "5. Regressions":         ...,
}

page = st.sidebar.radio(
    "Pipeline step",
    list(pipeline_status.keys()),
    format_func=lambda p: f"{status_badge(pipeline_status[p])}  {p}",
)

st.sidebar.markdown("---")
st.sidebar.caption(f"Project base:\n`{os.path.abspath(BASE)}`")
with st.sidebar.expander("Expected folder layout"):
    st.code(
        "dictionary/variables_master.xlsx\n"
        "baseline/02_dictionary/variables_personalized.csv   (from baseline pipeline Step 1)\n"
        "endline/02_dictionary/variables_personalized.csv    (from endline pipeline Step 1)\n"
        "harmonization/\n"
        "├── 02_dictionary/variables_personalized.csv   (generated by Step 1 below)\n"
        "├── 03_data/                    (combined baseline+endline data)\n"
        "├── 04_qualityCheck/\n"
        "├── 05_plots/\n"
        "└── 06_regressions/",
        language="text",
    )


# ── Page 1: Dictionary Merge ──────────────────────────────────────────────────
if page == "1. Dictionary Merge":
    s01.render(standalone=False)

# Future pages go here, following the same pattern as the individual app.py:
# elif page == "2. Combine Data":
#     s02.render(standalone=False)
