"""
AGEVAL Step 3 — Data Quality Checker
Run: python scripts/s03_quality_check.py --data data_raw/collected_data.csv
Run: python scripts/s03_quality_check.py --data data_raw/test_data_honduras_n200.csv

Reads collected ODK CSV export and applies quality rules from the dictionary.
Produces an HTML quality report per batch.
"""
 
import pandas as pd
import numpy as np
import os
import re
import yaml
import argparse
from datetime import datetime
from jinja2 import Template
 
BASE   = os.path.dirname(os.path.abspath(__file__))
ROOT   = os.path.join(BASE, "..")
CFG    = os.path.join(ROOT, "config", "config.yaml")
DICT   = os.path.join(ROOT, "dictionary", "variables_personalized.csv")
OUTDIR = os.path.join(ROOT, "outputs", "quality")
 
# ── HTML report template ───────────────────────────────────────────────────────
HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="UTF-8">
<title>AGEVAL Quality Report - {{ batch }}</title>
<style>
  body { font-family: -apple-system, sans-serif; max-width: 1100px; margin: 2rem auto; color: #1a1a1a; }
  h1   { font-size: 1.5rem; font-weight: 600; border-bottom: 2px solid #2563EB; padding-bottom: .5rem; }
  h2   { font-size: 1.1rem; font-weight: 600; margin-top: 2rem; color: #1D4ED8; }
  .summary-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 1rem; margin: 1.5rem 0; }
  .card { background: #F8FAFC; border: 1px solid #E2E8F0; border-radius: 8px; padding: 1rem; text-align: center; }
  .card .val { font-size: 2rem; font-weight: 700; }
  .card .lbl { font-size: .75rem; color: #64748B; margin-top: .25rem; }
  .ok   { color: #16A34A; }
  .warn { color: #D97706; }
  .err  { color: #DC2626; }
  table { width: 100%; border-collapse: collapse; font-size: .85rem; margin-top: .75rem; }
  th    { background: #1D4ED8; color: white; padding: .5rem .75rem; text-align: left; }
  td    { padding: .4rem .75rem; border-bottom: 1px solid #E2E8F0; }
  tr:nth-child(even) { background: #F8FAFC; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 9999px; font-size: .75rem; font-weight: 600; }
  .badge-err  { background: #FEE2E2; color: #991B1B; }
  .badge-warn { background: #FEF3C7; color: #92400E; }
  .badge-ok   { background: #D1FAE5; color: #065F46; }
  footer { margin-top: 3rem; font-size: .75rem; color: #94A3B8; }
</style>
</head>
<body>
<h1>AGEVAL Quality Report</h1>
<p>Batch: <strong>{{ batch }}</strong> &nbsp;|&nbsp; Generated: {{ generated }} &nbsp;|&nbsp; Records checked: <strong>{{ n_records }}</strong></p>
 
<div class="summary-grid">
  <div class="card"><div class="val ok">{{ n_records }}</div><div class="lbl">Total records</div></div>
  <div class="card"><div class="val warn">{{ n_warnings }}</div><div class="lbl">Warnings</div></div>
  <div class="card"><div class="val err">{{ n_errors }}</div><div class="lbl">Errors (out of range)</div></div>
  <div class="card"><div class="val">{{ n_vars_checked }}</div><div class="lbl">Variables checked</div></div>
</div>
 
{% for vname, result in results.items() %}
<h2>{{ vname }} <small style="font-weight:400; color:#64748B;">— {{ result.label }}</small></h2>
<table>
  <tr>
    <th>Check</th><th>Status</th><th>Detail</th>
  </tr>
  {% for check in result.checks %}
  <tr>
    <td>{{ check.name }}</td>
    <td><span class="badge badge-{{ check.status }}">{{ check.status.upper() }}</span></td>
    <td>{{ check.detail }}</td>
  </tr>
  {% endfor %}
</table>
 
{% if result.flagged_ids %}
<details>
  <summary style="cursor:pointer; margin-top:.5rem; font-size:.8rem; color:#1D4ED8;">
    Show {{ result.flagged_ids|length }} flagged records
  </summary>
  <table style="margin-top:.5rem;">
    <tr><th>Respondent ID</th><th>Value</th><th>Issue</th></tr>
    {% for rec in result.flagged_ids %}
    <tr><td>{{ rec.id }}</td><td>{{ rec.value }}</td><td>{{ rec.issue }}</td></tr>
    {% endfor %}
  </table>
</details>
{% endif %}
 
{% endfor %}
 
<footer>Generated by AGEVAL v1.0 — CIAT</footer>
</body>
</html>
"""
 
# ── Load config and functions  ─────────────────────────────────────────────────
cfg = yaml.safe_load(open(CFG))
# Extract global thresholds from config
cfg_duplicate_pct = cfg["quality"]["duplicate_pct"]
cfg_method        = cfg["quality"]["outlier_method"]
cfg_missing_warn  = cfg["quality"]["missing_warn"]
cfg_missing_err   = cfg["quality"]["missing_err"]
 
# ── Duplicate detection ─────────────────────────────────────────────────────────
def check_duplicates(report_data, id_col, compare_cols, cfg_duplicate_pct):
    checks = []
    flagged = []
 
    extra_cols = [c for c in ["respondent_id", "start", "end", "deviceid"] if c in report_data.columns]
 
    # 1. Exact respondent_id duplicates
    id_dup_mask = report_data[id_col].duplicated(keep=False) & report_data[id_col].notna()
    id_dups = report_data[id_dup_mask]
    for idx, r in id_dups.iterrows():
        flagged.append({
            "id": r.get(id_col, idx),
            "value": ", ".join(f"{c}={r.get(c, '')}" for c in extra_cols),
            "issue": "Duplicate ID",
        })
    checks.append({
        "name":   "Duplicate respondent_id",
        "status": "err" if len(id_dups) > 0 else "ok",
        "detail": f"{len(id_dups)} records with duplicate respondent_id",
    })
 
    # 2. Similarity duplicates — pairwise comparison across previously checked variables
    valid_compare_cols = [c for c in compare_cols if c in report_data.columns]
    n_cols = len(valid_compare_cols)
    sim_flagged = []
 
    if n_cols > 0:
        records = report_data[valid_compare_cols].reset_index(drop=True)
        ids     = report_data[id_col].reset_index(drop=True)
        extras  = report_data[extra_cols].reset_index(drop=True) if extra_cols else None
        n = len(records)
 
        for i in range(n):
            row_i = records.iloc[i]
            for j in range(i + 1, n):
                row_j = records.iloc[j]
                matches = (row_i == row_j) | (row_i.isna() & row_j.isna())
                pct = matches.sum() / n_cols * 100
 
                if pct >= cfg_duplicate_pct:
                    detail_extra = ""
                    if extras is not None:
                        detail_extra = " | ".join(
                            f"{c}: {extras.iloc[i][c]} / {extras.iloc[j][c]}" for c in extra_cols
                        )
                    sim_flagged.append({
                        "id":    f"{ids[i]} / {ids[j]}",
                        "value": f"{round(pct, 1)}%" + (f" — {detail_extra}" if detail_extra else ""),
                        "issue": "Potential duplicate based on similarity",
                    })
 
    checks.append({
        "name":   f"Similarity duplicates (≥{cfg_duplicate_pct}%)",
        "status": "warn" if len(sim_flagged) > 0 else "ok",
        "detail": f"{len(sim_flagged)} record pairs flagged out of {n_cols} compared variables",
    })
 
    flagged.extend(sim_flagged)
    return checks, flagged
 
 
# ── Shared ODK expression translation (used by relevance and constraint checks) ─
def odk_to_python_expr(expr, dot_col=None):
    """
    Convert an ODK-style expression (as used in `relevant` and `constraint`
    columns of XLSForms — stored here as `surv_relevant` / `surv_constraint`)
    into a Python-evaluable expression string that operates on a `row` dict.
 
    Supported translations:
      ${var}                -> row.get('var')
      .                      -> row.get(dot_col)  (ODK's "current field value"
                                placeholder, used in constraint expressions;
                                pass dot_col=<the field's own column name>)
      single '=' comparison -> '=='  (leaves ==, !=, <=, >= untouched)
      selected(${var},'x')  -> membership test against space-separated values
      and / or / not        -> pass through (valid Python keywords already)
    Returns None if the expression is empty/NaN.
    """
    if pd.isna(expr) or not str(expr).strip():
        return None
 
    e = str(expr).strip()
 
    # selected(${var}, 'value')  -> handled before ${..} substitution so we
    # can reference the raw variable name twice safely.
    def _selected_repl(m):
        var, val = m.group(1), m.group(2)
        return f"('{val}' in str(row.get('{var}') or '').split())"
    e = re.sub(r"selected\(\s*\$\{([a-zA-Z0-9_]+)\}\s*,\s*'([^']*)'\s*\)", _selected_repl, e)
 
    # ${var} -> row.get('var')
    e = re.sub(r"\$\{([a-zA-Z0-9_]+)\}", r"row.get('\1')", e)
 
    # standalone '.' (ODK's current-value placeholder, e.g. ". > 0") -> row.get(dot_col)
    # The lookaround avoids matching decimal points (e.g. "0.5", which are
    # always preceded by a digit) or dots that are part of another token.
    if dot_col is not None:
        e = re.sub(r"(?<![\w.])\.(?![\w.])", f"row.get('{dot_col}')", e)
 
    # single '=' to '==' without touching !=, <=, >=, == already present
    e = re.sub(r"(?<![=!<>])=(?!=)", "==", e)
 
    # ODK string literals use double quotes sometimes; Python is fine with both.
    return e
 
 
def coerce_numeric(value):
    """Try to coerce a value to float so that >, <, >=, <= comparisons in
    relevance/constraint expressions behave numerically instead of falling
    back to (incorrect) lexicographic string comparison. Non-numeric values
    (including NaN/None) are returned unchanged."""
    if value is None:
        return value
    try:
        if pd.isna(value):
            return value
    except (TypeError, ValueError):
        pass
    try:
        return float(value)
    except (TypeError, ValueError):
        return value
 
 
def _coerced_row_dict(row):
    return {k: coerce_numeric(v) for k, v in row.to_dict().items()}
 
 
def evaluate_relevance(expr_py, row_dict):
    """Evaluate a translated relevance expression against a row dict.
    Returns True/False, or None if it can't be evaluated (e.g. a dependency
    variable is not present in the data)."""
    if expr_py is None:
        return None
    try:
        return bool(eval(expr_py, {"__builtins__": {}}, {"row": row_dict}))
    except Exception:
        return None
 
 
def check_relevance(report_data, id_col, col, relevant_expr):
    """
    Flags:
      - records with a value in `col` even though `relevant_expr` evaluates
        to False (the field should have been skipped by the form logic).
      - records where `relevant_expr` evaluates to True but `col` is missing
        (the field was expected to be filled in — surface this alongside the
        existing missing-value rule so it can be reviewed together).
    """
    checks = []
    flagged = []
 
    expr_py = odk_to_python_expr(relevant_expr)
    if expr_py is None or col not in report_data.columns:
        return checks, flagged
 
    n_unexpected_value = 0
    n_unexpected_missing = 0
    n_unevaluable = 0
 
    for idx, r in report_data.iterrows():
        row_dict = _coerced_row_dict(r)
        is_relevant = evaluate_relevance(expr_py, row_dict)
        rid = r.get(id_col, idx)
 
        if is_relevant is None:
            n_unevaluable += 1
            continue
 
        value = r.get(col)
        has_value = pd.notna(value) and str(value).strip() != ""
 
        if not is_relevant and has_value:
            n_unexpected_value += 1
            flagged.append({
                "id":    rid,
                "value": value,
                "issue": f"Value present but relevance condition not met ({relevant_expr})",
            })
        elif is_relevant and not has_value:
            n_unexpected_missing += 1
            flagged.append({
                "id":    rid,
                "value": "(missing)",
                "issue": f"Relevance condition met ({relevant_expr}) but value is missing — review against quality rules",
            })
 
    checks.append({
        "name":   "Relevance: value present when not relevant",
        "status": "err" if n_unexpected_value > 0 else "ok",
        "detail": f"{n_unexpected_value} records have a value despite condition '{relevant_expr}' not being met",
    })
    checks.append({
        "name":   "Relevance: missing value when relevant",
        "status": "warn" if n_unexpected_missing > 0 else "ok",
        "detail": f"{n_unexpected_missing} records missing a value despite condition '{relevant_expr}' being met",
    })
    if n_unevaluable > 0:
        checks.append({
            "name":   "Relevance: condition could not be evaluated",
            "status": "warn",
            "detail": f"{n_unevaluable} records could not be evaluated (missing dependency variable(s) in '{relevant_expr}')",
        })
 
    return checks, flagged
 
 
# ── Constraint check (based on surv_constraint / ODK "constraint" expressions) ──
def check_constraint(report_data, id_col, col, constraint_expr):
    """
    ODK evaluates a field's `constraint` only when the field has a value,
    using '.' as the placeholder for that field's own value (e.g. ". > 0",
    ". >= 1 and . <= 10", ". > 0 and . <= ${area_total_farm_raw}").
 
    Flags every record whose value does NOT satisfy its constraint.
    """
    checks = []
    flagged = []
 
    if pd.isna(constraint_expr) or not str(constraint_expr).strip() or col not in report_data.columns:
        return checks, flagged
 
    expr_py = odk_to_python_expr(constraint_expr, dot_col=col)
    if expr_py is None:
        return checks, flagged
 
    n_violations = 0
    n_unevaluable = 0
 
    for idx, r in report_data.iterrows():
        value = r.get(col)
        has_value = pd.notna(value) and str(value).strip() != ""
        if not has_value:
            continue  # constraint only applies when a value is present, as in ODK
 
        rid = r.get(id_col, idx)
        row_dict = _coerced_row_dict(r)
 
        try:
            satisfied = bool(eval(expr_py, {"__builtins__": {}}, {"row": row_dict}))
        except Exception:
            n_unevaluable += 1
            continue
 
        if not satisfied:
            n_violations += 1
            flagged.append({
                "id":    rid,
                "value": value,
                "issue": f"Value {value!r} violates constraint ({constraint_expr})",
            })
 
    checks.append({
        "name":   f"Constraint ({constraint_expr})",
        "status": "err" if n_violations > 0 else "ok",
        "detail": f"{n_violations} records violate constraint '{constraint_expr}'",
    })
    if n_unevaluable > 0:
        checks.append({
            "name":   "Constraint: could not be evaluated",
            "status": "warn",
            "detail": f"{n_unevaluable} records could not be evaluated (missing dependency variable(s) in '{constraint_expr}')",
        })
 
    return checks, flagged
 
 
# ── Core quality checks ────────────────────────────────────────────────────────
def check_variable(series, row, id_series, reference_series=None):
    checks = []
    flagged = []
 
    if reference_series is None:
        reference_series = series
 
    # Extract variable-specific thresholds from the dictionary row
    vname   = row["variable_name"]
    label   = row.get("label_spanish", vname)
    vmin    = row.get("quality_min")
    vmax    = row.get("quality_max")
    sd_thr  = row.get("quality_outlier_sd")
 
    valid = series.dropna()
    n_total   = len(series)
    n_missing = (series.isna() | series.isin([555, 666, 777, 888, 999])).sum()
 
    # 1. Missing values (reported range only)
    pct_missing = round(n_missing / n_total * 100, 1) if n_total > 0 else 0
    checks.append({
        "name":   "Missing values",
        "status": "err" if pct_missing > cfg_missing_warn else ("warn" if pct_missing > cfg_missing_warn else "ok"),
        "detail": f"{n_missing}/{n_total} missing ({pct_missing}%)",
    })
 
    # 2. Range check (fixed thresholds — flagged within reported range only)
    if pd.notna(vmin) and pd.notna(vmax):
        numeric = pd.to_numeric(valid, errors="coerce").dropna()
        numeric = numeric[~numeric.isin([555, 666, 777, 888, 999])]
        out_of_range = numeric[(numeric < vmin) | (numeric > vmax)]
        for idx in out_of_range.index:
            flagged.append({"id": id_series.get(idx, idx), "value": numeric[idx], "issue": f"Out of range [{vmin}, {vmax}]"})
        checks.append({
            "name":   f"Range [{vmin} – {vmax}]",
            "status": "err" if len(out_of_range) > 0 else "ok",
            "detail": f"{len(out_of_range)} values out of range",
        })
 
    # 3. Outlier check — reference (mean/sd) from reference_series,
    #    flags raised only among the reported range.
    reference_numeric = pd.to_numeric(reference_series.dropna(), errors="coerce").dropna()
    reference_numeric = reference_numeric[~reference_numeric.isin([555, 666, 777, 888, 999])]
    if len(reference_numeric) > 4:
        numeric = pd.to_numeric(valid, errors="coerce").dropna()
        numeric = numeric[~numeric.isin([888, 999])]
 
        if cfg_method == "sd" and pd.notna(sd_thr) and sd_thr > 0:
            mean = reference_numeric.mean()
            sd = reference_numeric.std()
            lower = mean - sd_thr * sd
            upper = mean + sd_thr * sd
            check_name = f"Outlier (>{sd_thr} SD)"
            issue = f"Outlier (>{sd_thr} SD from mean {mean:.2f})"
            detail = (
                f"mean={mean:.2f}, sd={sd:.2f}, "
                f"reference n={len(reference_numeric)}"
            )
 
        elif cfg_method == "iqr":
            q1 = reference_numeric.quantile(0.25)
            q3 = reference_numeric.quantile(0.75)
            iqr = q3 - q1
            lower = q1 - 1.5 * iqr
            upper = q3 + 1.5 * iqr
            check_name = "Outlier (IQR)"
            issue = f"Outlier (outside [{lower:.2f}, {upper:.2f}])"
            detail = (
                f"Q1={q1:.2f}, Q3={q3:.2f}, IQR={iqr:.2f}, "
                f"reference n={len(reference_numeric)}"
            )
 
        outliers = numeric[(numeric < lower) | (numeric > upper)]
        for idx in outliers.index:
            flagged.append({
                "id": id_series.get(idx, idx),
                "value": round(numeric[idx], 2),
                "issue": issue,
            })
        checks.append({
            "name": check_name,
            "status": "warn" if len(outliers) else "ok",
            "detail": f"{len(outliers)} outliers detected ({detail})",
        })
 
    return checks, flagged, label
 
 
# ── Date filtering ──────────────────────────────────────────────────────────────
def filter_by_date(data, date_start=None, date_end=None, date_col="surveyDate"):
    if date_col not in data.columns:
        return data
    if not pd.api.types.is_datetime64_any_dtype(data[date_col]):
        data = data.copy()
        data[date_col] = pd.to_datetime(data[date_col], errors="coerce")
    if date_start is not None:
        data = data[data[date_col] >= pd.to_datetime(date_start)]
    if date_end is not None:
        data = data[data[date_col] <= pd.to_datetime(date_end)]
    return data
 
def get_available_dates(data_path, date_col="surveyDate"):
    try:
        data = pd.read_csv(data_path, usecols=lambda c: c == date_col)
    except (ValueError, FileNotFoundError):
        return []
    if date_col not in data.columns:
        return []
    dates = pd.to_datetime(data[date_col], errors="coerce").dropna().dt.date
    return sorted(dates.unique())
 
 
# ── Main ───────────────────────────────────────────────────────────────────────
def run_quality_check(data_path, batch_name=None, date_start=None, date_end=None, date_col="surveyDate"):
    with open(CFG) as f:
        cfg = yaml.safe_load(f)
 
    dict_df = pd.read_csv(DICT)
    qc_vars = dict_df[dict_df["quality_include"] == 1]
 
    data = pd.read_csv(data_path)
 
    # Reference: all records up to (and including) the selected end date,
    # regardless of start date — used only to compute statistical references.
    reference_data = filter_by_date(data, None, date_end, date_col)
    # Reported: records within the full selected range — these are the ones
    # actually checked/flagged and shown in the report.
    report_data = filter_by_date(data, date_start, date_end, date_col)
    n_records = len(report_data)
 
    # ID column for reporting
    id_col = "respondent_id" if "respondent_id" in report_data.columns else report_data.columns[0]
    id_series = report_data[id_col]
 
    batch = batch_name or os.path.basename(data_path).replace(".csv", "")
    results = {}
    total_warnings = 0
    total_errors   = 0
 
    compare_cols = [
        row.get("surv_calculation_output", row["variable_name"])
        if pd.notna(row.get("surv_calculation_output")) and row.get("surv_calculation_output") in report_data.columns
        else row["variable_name"]
        for _, row in qc_vars.iterrows()
    ]
    compare_cols = [c for c in compare_cols if c in report_data.columns]
 
    dup_checks, dup_flagged = check_duplicates(report_data, id_col, compare_cols, cfg_duplicate_pct)
    results["duplicates"] = {"label": "Duplicate detection", "checks": dup_checks, "flagged_ids": dup_flagged}
 
    for c in dup_checks:
        if c["status"] == "warn":
            total_warnings += 1
        elif c["status"] == "err":
            total_errors += 1
 
    for _, row in qc_vars.iterrows():
        vname = row["variable_name"]
        # Use calculated output column if available
        col = row.get("surv_calculation_output", vname)
        col = col if (pd.notna(col) and col in report_data.columns) else vname
 
        if col not in report_data.columns:
            continue
 
        reference_col = col if col in reference_data.columns else None
        checks, flagged, label = check_variable(
            report_data[col], row, id_series,
            reference_series=reference_data[reference_col] if reference_col else None,
        )
 
        # ── Relevance check ─────────────────────────────────────────────────
        relevant_expr = row.get("surv_relevant")
        if pd.notna(relevant_expr) and str(relevant_expr).strip():
            rel_checks, rel_flagged = check_relevance(report_data, id_col, col, relevant_expr)
            checks.extend(rel_checks)
            flagged.extend(rel_flagged)
 
        # ── Constraint check ─────────────────────────────────────────────────
        constraint_expr = row.get("surv_constraint")
        if pd.notna(constraint_expr) and str(constraint_expr).strip():
            con_checks, con_flagged = check_constraint(report_data, id_col, col, constraint_expr)
            checks.extend(con_checks)
            flagged.extend(con_flagged)
 
        results[vname] = {"label": label, "checks": checks, "flagged_ids": flagged}
 
        for c in checks:
            if c["status"] == "warn":
                total_warnings += 1
            elif c["status"] == "err":
                total_errors += 1
 
    # ── Render HTML report ─────────────────────────────────────────────────────
    tmpl = Template(HTML_TEMPLATE)
    html = tmpl.render(
        batch=batch,
        generated=datetime.now().strftime("%Y-%m-%d %H:%M"),
        n_records=n_records,
        n_warnings=total_warnings,
        n_errors=total_errors,
        n_vars_checked=len(results),
        results=results,
    )
 
    os.makedirs(OUTDIR, exist_ok=True)
    out_path  = os.path.join(OUTDIR, f"quality_report_{batch}.html")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(html)
 
    print(f"✅  Quality report saved: {out_path}")
    print(f"    Records checked:   {n_records}")
    print(f"    Variables checked: {len(results)}")
    print(f"    Warnings:          {total_warnings}")
    print(f"    Errors:            {total_errors}")
    return out_path
 
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="AGEVAL Quality Check")
    parser.add_argument("--data",  required=True, help="Path to collected CSV data file")
    parser.add_argument("--batch", default=None,  help="Batch name (optional label)")
    parser.add_argument("--date-start", default=None, help="Filter: only records on/after this date (YYYY-MM-DD)")
    parser.add_argument("--date-end",   default=None, help="Filter: only records on/before this date (YYYY-MM-DD)")
    parser.add_argument("--date-col",   default="surveyDate", help="Column name holding the survey date")
    args = parser.parse_args()
    run_quality_check(args.data, args.batch, args.date_start, args.date_end, args.date_col)