"""
AGEVAL Step 3 — Data Quality Checker
Run: python scripts/s03_quality_check.py --data data_raw/collected_data.csv

Reads collected ODK CSV export and applies quality rules from the dictionary.
Produces an HTML quality report per batch.
"""

import pandas as pd
import numpy as np
import os
import yaml
import argparse
from datetime import datetime
from jinja2 import Template

BASE   = os.path.dirname(os.path.abspath(__file__))
ROOT   = os.path.join(BASE, "..")
CFG    = os.path.join(ROOT, "config", "config.yaml")
DICT   = os.path.join(ROOT, "dictionary", "variables_personalized.csv")
OUTDIR = os.path.join(ROOT, "outputs", "quality")

# ── HTML report template ───────────────────────────────────────────────────────
HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="UTF-8">
<title>AGEVAL Quality Report — {{ batch }}</title>
<style>
  body { font-family: -apple-system, sans-serif; max-width: 1100px; margin: 2rem auto; color: #1a1a1a; }
  h1   { font-size: 1.5rem; font-weight: 600; border-bottom: 2px solid #2563EB; padding-bottom: .5rem; }
  h2   { font-size: 1.1rem; font-weight: 600; margin-top: 2rem; color: #1D4ED8; }
  .summary-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 1rem; margin: 1.5rem 0; }
  .card { background: #F8FAFC; border: 1px solid #E2E8F0; border-radius: 8px; padding: 1rem; text-align: center; }
  .card .val { font-size: 2rem; font-weight: 700; }
  .card .lbl { font-size: .75rem; color: #64748B; margin-top: .25rem; }
  .ok   { color: #16A34A; }
  .warn { color: #D97706; }
  .err  { color: #DC2626; }
  table { width: 100%; border-collapse: collapse; font-size: .85rem; margin-top: .75rem; }
  th    { background: #1D4ED8; color: white; padding: .5rem .75rem; text-align: left; }
  td    { padding: .4rem .75rem; border-bottom: 1px solid #E2E8F0; }
  tr:nth-child(even) { background: #F8FAFC; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 9999px; font-size: .75rem; font-weight: 600; }
  .badge-err  { background: #FEE2E2; color: #991B1B; }
  .badge-warn { background: #FEF3C7; color: #92400E; }
  .badge-ok   { background: #D1FAE5; color: #065F46; }
  footer { margin-top: 3rem; font-size: .75rem; color: #94A3B8; }
</style>
</head>
<body>
<h1>AGEVAL Quality Report</h1>
<p>Batch: <strong>{{ batch }}</strong> &nbsp;|&nbsp; Generated: {{ generated }} &nbsp;|&nbsp; Records checked: <strong>{{ n_records }}</strong></p>

<div class="summary-grid">
  <div class="card"><div class="val ok">{{ n_records }}</div><div class="lbl">Total records</div></div>
  <div class="card"><div class="val warn">{{ n_warnings }}</div><div class="lbl">Warnings</div></div>
  <div class="card"><div class="val err">{{ n_errors }}</div><div class="lbl">Errors (out of range)</div></div>
  <div class="card"><div class="val">{{ n_vars_checked }}</div><div class="lbl">Variables checked</div></div>
</div>

{% for vname, result in results.items() %}
<h2>{{ vname }} <small style="font-weight:400; color:#64748B;">— {{ result.label }}</small></h2>
<table>
  <tr>
    <th>Check</th><th>Status</th><th>Detail</th>
  </tr>
  {% for check in result.checks %}
  <tr>
    <td>{{ check.name }}</td>
    <td><span class="badge badge-{{ check.status }}">{{ check.status.upper() }}</span></td>
    <td>{{ check.detail }}</td>
  </tr>
  {% endfor %}
</table>

{% if result.flagged_ids %}
<details>
  <summary style="cursor:pointer; margin-top:.5rem; font-size:.8rem; color:#1D4ED8;">
    Show {{ result.flagged_ids|length }} flagged records
  </summary>
  <table style="margin-top:.5rem;">
    <tr><th>Record ID</th><th>Value</th><th>Issue</th></tr>
    {% for rec in result.flagged_ids %}
    <tr><td>{{ rec.id }}</td><td>{{ rec.value }}</td><td>{{ rec.issue }}</td></tr>
    {% endfor %}
  </table>
</details>
{% endif %}

{% endfor %}

<footer>Generated by AGEVAL v1.0 — CIAT</footer>
</body>
</html>
"""

# ── Core quality checks ────────────────────────────────────────────────────────
def check_variable(series, row, id_series):
    checks = []
    flagged = []

    vname   = row["variable_name"]
    label   = row.get("label_spanish", vname)
    vmin    = row.get("quality_min")
    vmax    = row.get("quality_max")
    sd_thr  = row.get("quality_outlier_sd")
    method  = "sd"  # from config ideally

    valid = series.dropna()
    n_total   = len(series)
    n_missing = series.isna().sum()

    # 1. Missing values
    pct_missing = round(n_missing / n_total * 100, 1) if n_total > 0 else 0
    checks.append({
        "name":   "Missing values",
        "status": "err" if pct_missing > 20 else ("warn" if pct_missing > 5 else "ok"),
        "detail": f"{n_missing}/{n_total} missing ({pct_missing}%)",
    })

    # 2. Range check
    if pd.notna(vmin) and pd.notna(vmax):
        numeric = pd.to_numeric(valid, errors="coerce").dropna()
        out_of_range = numeric[(numeric < vmin) | (numeric > vmax)]
        for idx in out_of_range.index:
            flagged.append({"id": id_series.get(idx, idx), "value": numeric[idx], "issue": f"Out of range [{vmin}, {vmax}]"})
        checks.append({
            "name":   f"Range [{vmin} – {vmax}]",
            "status": "err" if len(out_of_range) > 0 else "ok",
            "detail": f"{len(out_of_range)} values out of range",
        })

    # 3. Outlier check (SD)
    if pd.notna(sd_thr) and sd_thr > 0:
        numeric = pd.to_numeric(valid, errors="coerce").dropna()
        if len(numeric) > 4:
            mean, sd = numeric.mean(), numeric.std()
            outliers = numeric[np.abs(numeric - mean) > sd_thr * sd]
            for idx in outliers.index:
                flagged.append({"id": id_series.get(idx, idx), "value": round(numeric[idx], 2),
                                "issue": f"Outlier (>{sd_thr} SD from mean {round(mean,2)})"})
            checks.append({
                "name":   f"Outlier (>{sd_thr} SD)",
                "status": "warn" if len(outliers) > 0 else "ok",
                "detail": f"{len(outliers)} outliers detected (mean={round(mean,2)}, sd={round(sd,2)})",
            })

    return checks, flagged, label

# ── Main ───────────────────────────────────────────────────────────────────────
def run_quality_check(data_path, batch_name=None):
    with open(CFG) as f:
        cfg = yaml.safe_load(f)

    dict_df = pd.read_csv(DICT)
    qc_vars = dict_df[dict_df["quality_include"] == 1]

    data = pd.read_csv(data_path)
    n_records = len(data)

    # ID column for reporting
    id_col = "respondent_id" if "respondent_id" in data.columns else data.columns[0]
    id_series = data[id_col]

    batch = batch_name or os.path.basename(data_path).replace(".csv", "")
    results = {}
    total_warnings = 0
    total_errors   = 0

    for _, row in qc_vars.iterrows():
        vname = row["variable_name"]
        # Use calculated output column if available
        col = row.get("odk_calculate_output", vname)
        col = col if (pd.notna(col) and col in data.columns) else vname

        if col not in data.columns:
            continue

        checks, flagged, label = check_variable(data[col], row, id_series)
        results[vname] = {"label": label, "checks": checks, "flagged_ids": flagged}

        for c in checks:
            if c["status"] == "warn":
                total_warnings += 1
            elif c["status"] == "err":
                total_errors += 1

    # ── Render HTML report ─────────────────────────────────────────────────────
    tmpl = Template(HTML_TEMPLATE)
    html = tmpl.render(
        batch=batch,
        generated=datetime.now().strftime("%Y-%m-%d %H:%M"),
        n_records=n_records,
        n_warnings=total_warnings,
        n_errors=total_errors,
        n_vars_checked=len(results),
        results=results,
    )

    os.makedirs(OUTDIR, exist_ok=True)
    ts        = datetime.now().strftime("%Y%m%d_%H%M")
    out_path  = os.path.join(OUTDIR, f"quality_report_{batch}_{ts}.html")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(html)

    print(f"✅  Quality report saved: {out_path}")
    print(f"    Records checked:   {n_records}")
    print(f"    Variables checked: {len(results)}")
    print(f"    Warnings:          {total_warnings}")
    print(f"    Errors:            {total_errors}")
    return out_path

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="AGEVAL Quality Check")
    parser.add_argument("--data",  required=True, help="Path to collected CSV data file")
    parser.add_argument("--batch", default=None,  help="Batch name (optional label)")
    args = parser.parse_args()
    run_quality_check(args.data, args.batch)
